/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltcore_network_FSocket */

#ifndef _Included_org_voltcore_network_FSocket
#define _Included_org_voltcore_network_FSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_voltcore_network_FSocket
 * Method:    openAndBind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_FSocket_openAndBind
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_voltcore_network_FSocket
 * Method:    accept
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_FSocket_accept
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_voltcore_network_FSocket
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSocket_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
