/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltcore_network_FSocketConn */

#ifndef _Included_org_voltcore_network_FSocketConn
#define _Included_org_voltcore_network_FSocketConn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_voltcore_network_FSocketConn
 * Method:    read
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_voltcore_network_FSocketConn_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_voltcore_network_FSocketConn
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSocketConn_write
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     org_voltcore_network_FSocketConn
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSocketConn_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
