/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltcore_network_FSelect */

#ifndef _Included_org_voltcore_network_FSelect
#define _Included_org_voltcore_network_FSelect
#ifdef __cplusplus
extern "C" {
#endif
#undef org_voltcore_network_FSelect_MAX_EVENTS
#define org_voltcore_network_FSelect_MAX_EVENTS 1024L
/*
 * Class:     org_voltcore_network_FSelect
 * Method:    fInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSelect_fInit
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_FSelect
 * Method:    fOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_FSelect_fOpen
  (JNIEnv *, jobject);

/*
 * Class:     org_voltcore_network_FSelect
 * Method:    fRegister
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSelect_fRegister
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_voltcore_network_FSelect
 * Method:    fSelect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSelect_fSelect
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_voltcore_network_FSelect
 * Method:    indicateReadyForWrite
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSelect_indicateReadyForWrite
  (JNIEnv *, jobject);

/*
 * Class:     org_voltcore_network_FSelect
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_network_FSelect_write
  (JNIEnv *, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
