/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltcore_network_TimeTracker2 */

#ifndef _Included_org_voltcore_network_TimeTracker2
#define _Included_org_voltcore_network_TimeTracker2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBEnableTracing
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBEnableTracing
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBDumpTraces
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBDumpTraces
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBLibcWrite
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBLibcWrite
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBLibcWriteReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBLibcWriteReturn
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBLibcRead
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBLibcRead
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBLibcReadReturn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBLibcReadReturn
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBWorkQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBWorkQueue
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBWorkRecv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBWorkRecv
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBWorkStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBWorkStart
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBLocalCommStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBLocalCommStart
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBLocalCommEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBLocalCommEnd
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBWorkSend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBWorkSend
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBResponseQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBResponseQueue
  (JNIEnv *, jclass);

/*
 * Class:     org_voltcore_network_TimeTracker2
 * Method:    VoltDBWorkEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_network_TimeTracker2_VoltDBWorkEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
