DROP PROCEDURE DoGetUser    IF EXISTS;
DROP PROCEDURE DoInsertUser IF EXISTS;
DROP TABLE TestUsers        IF EXISTS;

CREATE TABLE TestUsers (
    u_id INTEGER NOT NULL,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL,
    photo VARCHAR(32),
    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_Users PRIMARY KEY (u_id)
);
PARTITION TABLE TestUsers ON COLUMN u_id;

LOAD CLASSES breakdown-procs.jar;

CREATE PROCEDURE PARTITION ON TABLE TestUsers COLUMN u_id FROM CLASS breakdown.DoGetUser;
CREATE PROCEDURE PARTITION ON TABLE TestUsers COLUMN u_id FROM CLASS breakdown.DoInsertUser;